cluster.name: "elasticsearch_atlas_production"
network.host: 0.0.0.0
gateway.recover_after_nodes: 1
gateway.expected_nodes: 1
gateway.recover_after_time: 5m
discovery.zen.minimum_master_nodes: 1
xpack.security.enabled: true

